name: Publish appimage anisette_server

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build and upload appimage
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'ubuntu-latest'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Installing Dependencies
        run: sudo add-apt-repository universe && sudo apt-get update && sudo apt-get install libfuse2 ca-certificates usbmuxd libimobiledevice6 libimobiledevice-utils libavahi-compat-libdnssd-dev curl -y && sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/ && dpkg -L ca-certificates usbmuxd libimobiledevice6 libimobiledevice-utils libavahi-compat-libdnssd-dev
      - name: Install LinuxDeploy
        uses: miurahr/install-linuxdeploy-action@v1
        with:
          plugins: qt appimage
      - name: Adding appimage contents
        run: sudo mv ./docker-entrypoint.sh ./Altcon.AppDir/usr/bin/ && sudo chmod +x ./Altcon.AppDir/AppRun && sudo chmod +x ./Altcon.AppDir/run.desktop && sudo chmod +x ./Altcon.AppDir/usr/bin/docker-entrypoint.sh && sudo mv ./get-altserver.sh ./Altcon.AppDir/usr/bin && cd ./Altcon.AppDir/usr/bin && sudo chmod +x ./get-altserver.sh
      - name: Install Altserver-Linux
        run: cd ./Altcon.AppDir/usr/bin && ./get-altserver.sh
      - name: Run linuxdeploy
        run: linuxdeploy-x86_64.AppImage --appdir=./Altcon.AppDir --output=appimage
        
