name: Publish appimage anisette_server

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build and upload appimage
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'ubuntu-20.04'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      #- name: Creating appdir
      #  run: mkdir Altcon
      #- name: Creating Directorys
      #  run: cd Altcon && mkdir usr && mkdir bin
        
