name: Publish appimage anisette_server

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build and upload appimage
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'ubuntu-latest'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Installing Dependencies
        run: sudo apt-get update && sudo apt-get install ca-certificates usbmuxd libimobiledevice6 libimobiledevice-utils libavahi-compat-libdnssd-dev curl -y && sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/ && ./docker-entrypoint.sh && ./get-altserver.sh

        
